[package]
name = "darkscraper-parser"
version = "0.1.0"
edition = "2021"

[dependencies]
darkscraper-core = { path = "../core" }
scraper = "0.21"
regex = "1"
once_cell = "1"
sha2 = "0.10"
tracing = { workspace = true }
url = { workspace = true }
chrono = { workspace = true }
